modLoader="javafml"
loaderVersion="[${loader_version},)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/Yunus1903/PortalInterfaces/issues"

[[mods]]
    modId="portalinterfaces"
    version="${version}"
    displayName="Portal Interfaces"
    displayURL=""
    logoFile=""

    authors="Yunus1903 & TheKayneGame"
    credits=""
    description="Adding item, fluid & power interfaces to nether portals"

[[dependencies.portalinterfaces]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.portalinterfaces]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
